- README.md
Submitted a PR to ensure CI system works.
> Fix copy and paste error for the CI badge

- src/NuProj.Targets/NuProj.targets
- src/NuProj.Tests/DependencyTests.cs
- src/NuProj.Tests/Scenarios/Dependency_IsBuilt_WhenNotBuildingInsideVisualStudio/ClassLibrary/ClassLibrary.csproj
- src/NuProj.Tests/Scenarios/Dependency_IsBuilt_WhenNotBuildingInsideVisualStudio/Dependency_IsBuilt_WhenNotBuildingInsideVisualStudio.sln
- src/NuProj.Tests/Scenarios/Dependency_IsBuilt_WhenNotBuildingInsideVisualStudio/NuGetDependency/NuGetDependency.nuproj
- src/NuProj.Tests/Scenarios/Dependency_IsBuilt_WhenNotBuildingInsideVisualStudio/NuGetDependency/Readme.txt
- src/NuProj.Tests/Scenarios/Dependency_IsNotBuilt_WhenBuildingInsideVisualStudio/NuGetDependency/NuGetDependency.nuproj
- src/NuProj.Tests/Scenarios/Dependency_IsNotBuilt_WhenBuildingInsideVisualStudio/NuGetDependency/Readme.txt
> Build all references. Fix for issue #32.

- docs/Authoring.md
- src/NuProj.Targets/NuProj.targets
- src/NuProj.Tasks/AssignTargetFramework.cs
- src/NuProj.Tasks/Extensions.cs
- src/NuProj.Tasks/GenerateNuSpec.cs
- src/NuProj.Tasks/Metadata.cs
- src/NuProj.Tasks/NuProj.Tasks.csproj
- src/NuProj.Tasks/ReadPackagesConfig.cs
- src/NuProj.Templates/NuGetPackage.nuproj
- src/NuProj.Tests/GenerateNuSpecTests.cs
- src/NuProj.Tests/Infrastructure/Extensions.cs
- src/NuProj.Tests/Infrastructure/ManifestDependencyComparer.cs
- src/NuProj.Tests/Infrastructure/ManifestDependencySetComparer.cs
- src/NuProj.Tests/Infrastructure/ManifestFileComparer.cs
- src/NuProj.Tests/Infrastructure/ManifestFrameworkAssemblyComparer.cs
- src/NuProj.Tests/Infrastructure/ManifestReferenceComparer.cs
- src/NuProj.Tests/Infrastructure/ManifestReferenceSetComparer.cs
- src/NuProj.Tests/NuProj.Tests.csproj
- src/NuProj.Tests/Scenarios/Task_GenerateNuSpec/NuGetPackage.nuspec
> Nuspec template

- src/NuProj.Targets/NuProj.targets
- src/NuProj.Tests/DependencyTests.cs
- src/NuProj.Tests/Infrastructure/PackageDependencyComparer.cs
- src/NuProj.Tests/Infrastructure/PackageDependencySetComparer.cs
- src/NuProj.Tests/NuProj.Tests.csproj
- src/NuProj.Tests/Scenarios/Dependency_MultipleFrameworks_AreResolved/Dependency.nuget/Dependency.nuget.nuproj
- src/NuProj.Tests/Scenarios/Dependency_MultipleFrameworks_AreResolved/Dependency.nuget/Readme.txt
- src/NuProj.Tests/Scenarios/Dependency_MultipleFrameworks_AreResolved/Dependency/Class1.cs
- src/NuProj.Tests/Scenarios/Dependency_MultipleFrameworks_AreResolved/Dependency/Dependency.net40.csproj
- src/NuProj.Tests/Scenarios/Dependency_MultipleFrameworks_AreResolved/Dependency/Dependency.net45.csproj
- src/NuProj.Tests/Scenarios/Dependency_MultipleFrameworks_AreResolved/Dependency/Properties/AssemblyInfo.cs
- src/NuProj.Tests/Scenarios/Dependency_MultipleFrameworks_AreResolved/Dependency_MultipleFrameworks_AreResolved.sln
- src/NuProj.Tests/Scenarios/Dependency_MultipleFrameworks_AreResolved/Dependent.nuget/Dependent.nuget.nuproj
- src/NuProj.Tests/Scenarios/Dependency_MultipleFrameworks_AreResolved/Dependent.nuget/Readme.txt
- src/NuProj.Tests/Scenarios/Dependency_MultipleFrameworks_AreResolved/Dependent/Class1.cs
- src/NuProj.Tests/Scenarios/Dependency_MultipleFrameworks_AreResolved/Dependent/Dependent.net40.csproj
- src/NuProj.Tests/Scenarios/Dependency_MultipleFrameworks_AreResolved/Dependent/Dependent.net45.csproj
- src/NuProj.Tests/Scenarios/Dependency_MultipleFrameworks_AreResolved/Dependent/Properties/AssemblyInfo.cs
> Assign target framework to NuProj dependencies. 

- src/NuProj.Targets/NuProj.targets
Fix #69. Simple approach, but gets the job done.
> Add returns for Build and Rebuild targets

- src/NuProj.Packages/NuProj.nuproj
Clarify wording in NuProj Build NuGet description
> Add clarification for visual studio extension link

- src/.nuget/packages.config
- src/NuProj.Packages/NuProj.nuproj
- src/NuProj.Setup/Feature.BuildIntegration.wxs
- src/NuProj.Tasks/NuProj.Tasks.csproj
- src/NuProj.Tasks/packages.config
- src/NuProj.Tests/DependencyTests.cs
- src/NuProj.Tests/GenerateNuSpecTests.cs
- src/NuProj.Tests/Infrastructure/Assets.cs
- src/NuProj.Tests/NuProj.Tests.csproj
- src/NuProj.Tests/Scenarios/Task_GenerateNuSpec/NuGetPackage.nuspec
- src/NuProj.Tests/packages.config
- src/NuProj.sln
- tools/package.proj
- tools/tests.proj
Updated NuGet packages to 2.8.5 and xUnit packages to 2.0.0 (stable).
> Updated NuGet dependencies to latest stable version.

- src/NuProj.Packages/NuProj.nuproj
- src/NuProj.Tasks/NuProj.Tasks.csproj
> Add XAML rules to NuProj.nupkg

- src/NuProj.ProjectSystem.12/Rules/general.xaml
- src/NuProj.Tests/DependencyTests.cs
- src/NuProj.Tests/Scenarios/Dependency_OmitDevelopmentDependencies/ClassLibrary1/Class1.cs
- src/NuProj.Tests/Scenarios/Dependency_OmitDevelopmentDependencies/ClassLibrary1/ClassLibrary1.csproj
- src/NuProj.Tests/Scenarios/Dependency_OmitDevelopmentDependencies/ClassLibrary1/Properties/AssemblyInfo.cs
- src/NuProj.Tests/Scenarios/Dependency_OmitDevelopmentDependencies/ClassLibrary1/packages.config
- src/NuProj.Tests/Scenarios/Dependency_OmitDevelopmentDependencies/Dependency_OmitDevelopmentDependencies.sln
- src/NuProj.Tests/Scenarios/Dependency_OmitDevelopmentDependencies/NuGetPackage1/NuGetPackage1.nuproj
Add test that verifies #109 isn't a bug with nuproj, but rather a bug in nuget/home#520
Fix #109
> Add test to verify support for developmentDependency=true

- src/NuProj.Targets/NuProj.targets
- src/NuProj.Tests/CreatePackageTests.cs
- src/NuProj.Tests/NuProj.Tests.csproj
- src/NuProj.Tests/Scenarios/CreatePackage_LibraryWithXmlDoc_ShouldNotFail/CreatePackage_LibraryWithXmlDoc_ShouldNotFail.sln
- src/NuProj.Tests/Scenarios/CreatePackage_LibraryWithXmlDoc_ShouldNotFail/Library/Class1.cs
- src/NuProj.Tests/Scenarios/CreatePackage_LibraryWithXmlDoc_ShouldNotFail/Library/Library.csproj
- src/NuProj.Tests/Scenarios/CreatePackage_LibraryWithXmlDoc_ShouldNotFail/Library/Properties/AssemblyInfo.cs
- src/NuProj.Tests/Scenarios/CreatePackage_LibraryWithXmlDoc_ShouldNotFail/Package/Package.nuproj
- src/NuProj.Tests/Scenarios/CreatePackage_LibraryWithXmlDoc_ShouldNotFail/Package/Readme.txt
Please review and merge, this is fix for #106.
> Fix failing build with enabled XML documentation. Issue 106 

- src/NuProj.Targets/NuProj.targets
- src/NuProj.Tests/ExtensibilityTests.cs
- src/NuProj.Tests/NuProj.Tests.csproj
- src/NuProj.Tests/Scenarios/Extensibility_LoadsDotUserFile/NuGetPackage/NuGetPackage.nuproj
- src/NuProj.Tests/Scenarios/Extensibility_LoadsDotUserFile/NuGetPackage/NuGetPackage.nuproj.user
- src/NuProj.Tests/Scenarios/Extensibility_LoadsDotUserFile/NuGetPackage/Readme.txt
> Import .user file

- docs/Build.md
- src/NuProj.Packages/NuProj.Common.nuproj
Package that provides _NuProjProjectReferenceClosure target.
> Nuproj.Common package for non-NuProj projects

- src/NuProj.Packages/NuProj.Common.nuproj
- src/NuProj.Packages/NuProj.nuproj
> Removed NuProj as a dependency.

- src/NuProj.Build/NuProj.Build.csproj
- src/NuProj.Tasks/NuProj.Tasks.csproj
- src/NuProj.Tests/Infrastructure/NuGetHelper.cs
- src/NuProj.Tests/NuProj.Tests.csproj
- src/NuProj.Tests/packages.config
Get the solution building and tests running again on a machine with only VS2015 installed.
> Engineering goodness

- src/NuProj.Tests/Scenarios/Extensibility_LoadsDotUserFile/NuGetPackage/NuGetPackage.nuproj.user
> Renamed conflicting AfterBuild target.

- src/NuProj.Targets/NuProj.targets
- src/NuProj.Tests/ExtensibilityTests.cs
- src/NuProj.Tests/Infrastructure/MSBuild.cs
- src/NuProj.Tests/Infrastructure/Scenario.cs
- src/NuProj.Tests/ReferenceTests.cs
- src/NuProj.Tests/Scenarios/References_ExcludeFromNuPkgAndEmbedSourceFiles/ClassLibrary39/Class1.cs
- src/NuProj.Tests/Scenarios/References_ExcludeFromNuPkgAndEmbedSourceFiles/ClassLibrary39/ClassLibrary39.csproj
- src/NuProj.Tests/Scenarios/References_ExcludeFromNuPkgAndEmbedSourceFiles/ClassLibrary39/Properties/AssemblyInfo.cs
- src/NuProj.Tests/Scenarios/References_ExcludeFromNuPkgAndEmbedSourceFiles/NuGetPackage/NuGetPackage.nuproj
- src/NuProj.Tests/Scenarios/References_ExcludeFromNuPkgAndEmbedSourceFiles/NuGetPackage/Readme.txt
- src/NuProj.Tests/Scenarios/References_ExcludeFromNuPkgAndEmbedSourceFiles/References_ExcludeFromNuPkgAndEmbedSourceFiles.sln
I also added optional MSBuild test logging.
Fixes #172
> Fix build break when embed source files is combined with ExcludeFromNuPkg

- src/NuProj.ProjectSystem.12/Rules/general.xaml
- src/NuProj.Targets/NuProj.targets
- src/NuProj.Tasks/NuGetPack.cs
Review and merge #184 first, as this PR builds on it.
Fix #183
> Add support for NuSpec macro properties

- src/NuProj.Targets/NuProj.targets
- src/NuProj.Tests/NuProj.Tests.csproj
- src/NuProj.Tests/PackageSpecificTests.cs
- src/NuProj.Tests/Scenarios/PackageSpecific_MicrosoftBclBuild/PackageSpecific_MicrosoftBclBuild.sln
- src/NuProj.Tests/Scenarios/PackageSpecific_MicrosoftBclBuild/Test/Test.nuproj
- src/NuProj.Tests/Scenarios/PackageSpecific_MicrosoftBclBuild/TestLibrary/Class1.cs
- src/NuProj.Tests/Scenarios/PackageSpecific_MicrosoftBclBuild/TestLibrary/Properties/AssemblyInfo.cs
- src/NuProj.Tests/Scenarios/PackageSpecific_MicrosoftBclBuild/TestLibrary/TestLibrary.csproj
- src/NuProj.Tests/Scenarios/PackageSpecific_MicrosoftBclBuild/TestLibrary/packages.config
> Reordered target calling so that Microsoft.Bcl.Build works.

- src/NuProj.Targets/NuProj.targets
- src/NuProj.Tests/BuildAuthoringTests.cs
- src/NuProj.Tests/Scenarios/BuildAuthoring_P2P_ResolvedPathHasComputedVersion/BuildAuthoring_P2P_ResolvedPathHasComputedVersion.sln
- src/NuProj.Tests/Scenarios/BuildAuthoring_P2P_ResolvedPathHasComputedVersion/NuGetWithComputedVersion/NuGetWithComputedVersion.nuproj
- src/NuProj.Tests/Scenarios/BuildAuthoring_P2P_ResolvedPathHasComputedVersion/NuGetWithComputedVersion/Readme.txt
- src/NuProj.Tests/Scenarios/BuildAuthoring_P2P_ResolvedPathHasComputedVersion/NuProjReferencingOtherNuProj/NuProjReferencingOtherNuProj.nuproj
- src/NuProj.Tests/Scenarios/BuildAuthoring_P2P_ResolvedPathHasComputedVersion/NuProjReferencingOtherNuProj/Readme.txt
> Fix P2P references between NuProj with computed versions

- src/NuProj.ProjectSystem.12/NuProj.ProjectSystem.12.csproj
- src/NuProj.ProjectSystem.12/packages.config
> Fix build on machines without VS2013

- src/NuProj.ProjectSystem.12/source.extension.vsixmanifest
- src/NuProj.ProjectSystem.14/source.extension.vsixmanifest
- src/NuProj.ProjectSystem.15/source.extension.vsixmanifest
Gets VSIX's so they can be uploaded to a myget.org feed to fix #240
> Distinguish VSIX versions

- docs/Authoring.md
- src/NuProj.ProjectSystem.Shared/Rules/ProjectReference.xaml
- src/NuProj.ProjectSystem.Shared/Rules/ResolvedProjectReference.xaml
- src/NuProj.Targets/NuProj.targets
- src/NuProj.Tasks/AssignTargetFramework.cs
- src/NuProj.Tasks/Extensions.cs
- src/NuProj.Tasks/Metadata.cs
- src/NuProj.Tasks/PackageDirectory.cs
- src/NuProj.Tests/ReferenceTests.cs
- src/NuProj.Tests/Scenarios/DotNet_CanPackage/Portable50Project/project.lock.json
- src/NuProj.Tests/Scenarios/References_PackageDirectory/PackageToAnalyzers/PackageToAnalyzers.nuproj
- src/NuProj.Tests/Scenarios/References_PackageDirectory/References_PackageDirectory.sln
- src/NuProj.sln
> Support for analyzers and custom target subdirectories

- src/NuProj.Packages/NuProj.nuproj
- src/NuProj.Targets/NuProj.targets
- src/NuProj.sln
> Package assemblies from NuGet cache

- src/NuProj.ProjectSystem.12/project.json
- src/NuProj.ProjectSystem.14/project.json
- src/NuProj.ProjectSystem.15/project.json
- src/NuProj.ProjectSystem.Shared/Rules/ResolvedProjectReference.xaml
- src/NuProj.Targets/NuProj.targets
> Fixed resolved project references

- docs/Authoring.md
- src/NuProj.Targets/NuProj.targets
- src/NuProj.Tasks/AssignPackageDirectory.cs
- src/NuProj.Tasks/Extensions.cs
- src/NuProj.Tasks/GenerateNuSpec.cs
- src/NuProj.Tests/CreatePackageTests.cs
- src/NuProj.Tests/Scenarios/CreatePackage_SetContentFilesMetadata/Package/Class1.cs.pp
- src/NuProj.Tests/Scenarios/CreatePackage_SetContentFilesMetadata/Package/Package.nuproj
> Unified linked and non-linked file behavior
