- README.md
- tools/build.proj
We use this ability to allow AppVeyor to discover the tests. Otherwise
the tests are run twice.
> Add ability to disable test runs

- src/NuProj.Targets/NuProj.props
- src/NuProj.Targets/NuProj.targets
- src/NuProj.Tasks/NuGetPack.cs
Per email, I've implemented this in the same manner as the existing NoPackageAnalysis property/parameter.
> Expose NuGet.exe's NoDefaultExcludes option to prevent exclusion of files/folders starting with '.' (fixes #67).

- .gitignore
Dev14 moves a lot of no-SCC files into a new hidden .vs folder. Make git ignore it.
> Ignore .vs folder.

- src/NuProj.Targets/NuProj.targets
In our build we extend the expand project references and would like to have metadata flow to this point.
> Preserve metadata on project references

- src/Common/CommonAssemblyInfo.cs
- src/NuProj.Package/source.extension.vsixmanifest
The increment of the minor version rather than the patch version is based on the fact that significant and backward breaking changes have been made. Yes, the nuget package is "unstable" right now (which is why we're not obliged to increment the major component), but we should try to communicate to consumers that something more than a simple patch update has been applied. And the minor component seems like the best place to do that.
> Update version from 0.9.3 to 0.10.0

- README.md
I didn't update the references to the badges after the org changes which caused them to be stale. This fixes that.
Please note the AppVeyor URL didn't change because those aren't associated with the org but with the user owning the build.
> Fix badges to match new org structure

- src/NuProj.ProjectSystem.14/NuProj.ProjectSystem.14.csproj
- src/NuProj.ProjectSystem.14/packages.config
Note that this adds more references to the project than existed before. This is because the transitive closure of assembly references are brought in, as is the style of nuget packages.
> Switch to CPS NuGet packages

- src/NuProj.Tests/NuProj.Tests.csproj
- src/NuProj.Tests/app.config
Before this, Xunit2 would show fully-qualified test methods (with namespace and class) in its list, which is redundant with the test class name which has been embedded in each test method's own name.
Eventually the "right" fix is probably to simplify all our test method names and then revert this change. But that will be considerably more work, and in the meantime this commit will make the UI more accessible."
> Xunit to display only test method names

- src/NuProj.Targets/NuProj.targets
This is a popular target from Microsoft.Common.targets but NuProj didn't import or define it. This caused issues when a NuGet package with a .props or .targets import is installed into a NuProj itself, and the NuGet package manager adds a target to the NuProj that runs with PrepareForBuild, but since we didn't define the target, NuGet's own target never ran.
Fixes #116
> Add PrepareForBuild target

- src/NuProj.Targets/NuProj.targets
- src/NuProj.Tasks/NuProj.Tasks.csproj
- src/NuProj.Tests/Infrastructure/MSBuild.cs
I added a verifier that runs with every test to cause a test failure if double-build ever occurs. 
Then I removed the test code that sets the `CustomAfterMicrosoftCommonTargets` global property for every build request because that masks the bug in the nuproj.targets file. Users don't set that global property, and the fact that the test does made it appear everywhere, resulting in only a single build in each project even though for the user, double builds result.
Finally, with the bug exposed and tests now failing, I removed the code in NuProj.targets that caused the double-build. I did not see any regressions in the tests from its removal (which was disappointing as this probably _does_ regress something), but I suspect that whatever regressed is less important than fixing frequent timing …
> Avoid double-build of referenced projects

- src/NuProj.Packages/NuProj.Common.nuproj
Prevents consuming .csproj project to list NuProj.Common as dependency.
> Set DevelopmentDependency to True  for NuProj.Common

- src/NuProj.Tests/Infrastructure/NuGetHelper.cs
Right after calling TCS.SetException we inevitably went on to call SetResult which will of course throw. We now ensure that we only call one or the other.
Fix #143
> Fix InvalidOperationException thrown when NuGet restore fails

- src/NuProj.Targets/NuProj.targets
- src/NuProj.Tests/Infrastructure/Assets.cs
- src/NuProj.Tests/ReferenceTests.cs
- src/NuProj.Tests/Scenarios/References_AssignProjectConfiguration/Debug_x64/Class1.cs
- src/NuProj.Tests/Scenarios/References_AssignProjectConfiguration/Debug_x64/Debug_x64.csproj
- src/NuProj.Tests/Scenarios/References_AssignProjectConfiguration/Debug_x64/Properties/AssemblyInfo.cs
- src/NuProj.Tests/Scenarios/References_AssignProjectConfiguration/Package/Package.nuproj
- src/NuProj.Tests/Scenarios/References_AssignProjectConfiguration/References_AssignProjectConfiguration.sln
- src/NuProj.Tests/Scenarios/References_AssignProjectConfiguration/Release_x86/Class1.cs
- src/NuProj.Tests/Scenarios/References_AssignProjectConfiguration/Release_x86/Properties/AssemblyInfo.cs
- src/NuProj.Tests/Scenarios/References_AssignProjectConfiguration/Release_x86/Release_x86.csproj
- src/NuProj.sln
Resolves #119. Uses `AssignProjectConfiguration` task to assign project configuration and platform to build references, as defined in solution.
> Use solution configuration when building references

- src/NuProj.Packages/NuProj.Common.nuproj
- src/NuProj.Targets/Redirect.targets
- src/NuProj.Tasks/NuProj.Tasks.csproj
The problem with the old mechanism is that the imported .targets file was directly in the NuGet package's build folder, which NuGet interprets as implying "net40". So it doesn't work with other platforms or PCLs. This fix puts a redirecting .targets file in the dotnet and a portable-* folder.
Fix #160
> Import NuProj.Common.targets in all project types

- src/NuProj.Setup/NuProj.Setup.wixproj
- tools/binaries.proj
This removes the requirement for the WiX toolset to be installed in order to build on dev boxes (or in the cloud)
In fact we already have the WiX toolset dependency brought in via NuGet, but the WiX project wasn't using it. This change makes it set up the properties to use it.
> Build using the NuGet package delivered WiX toolset

- src/NuProj.Tasks/GenerateNuSpec.cs
- src/NuProj.Tests/GenerateNuSpecTests.cs
Sample usage:
```
<Dependency Include="_._">
<TargetFramework>net46</TargetFramework>
</Dependency>
```
An empty dependency group is needed when you support a platform but don't need any dependencies but another group (for example an earlier framework) required dependencies.
> Add support for placeholder dependency indicating empty dependency group

- src/NuProj.ProjectSystem.12/Rules/general.xaml
- src/NuProj.Targets/NuProj.props
- src/NuProj.Targets/NuProj.targets
While in there, I went ahead and categorized all the existing properties as either build related or NuSpec properties.
Fix #180
> Expose OutputPath in property dialog

- src/.nuget/packages.config
- src/NuProj.Packages/NuProj.nuproj
- src/NuProj.Setup/Feature.BuildIntegration.wxs
- src/NuProj.Tasks/NuProj.Tasks.csproj
- src/NuProj.Tests/BasicTests.cs
- src/NuProj.Tests/Infrastructure/Assets.cs
- src/NuProj.Tests/Infrastructure/MSBuild.cs
- src/NuProj.Tests/Infrastructure/ProjectBuilder.cs
- src/NuProj.Tests/NuProj.Tests.csproj
- src/NuProj.Tests/app.config
- src/NuProj.Tests/packages.config
- tools/package.proj
Build against MSBuild 12, and test using MSBuild 14 to later enable adding tests for project.json support, which requires MSBuild 14.
Before this, we were using MSBuild 4 in tests, which NuProj itself never supported. By building the product against MSBuild 12, we don't cut support for any previously supported versions. By testing against MSBuild 14, we open up the opportunity to test project.json.
> Use MSBuild 12/14

- src/NuProj.Targets/NuProj.targets
Update <UsingTask /> of "AssignProjectConfiguration" for MSBuild 14.0 and above
In MSBuild 14.0, the tasks assembly was renamed to Microsoft.Build.Tasks.Core.dll.  So this condition will work for MSBuild 14.0 and above.
Fixes #257
> Support for MSBuild 14.0+

- src/NuProj.Packages/NuProj.nuproj
- src/NuProj.Packages/build/NuProj.props
Fixes issue #277 
Though I got to thinking as I was manually testing it, that:
1. Without property support in nuget.exe to support _*.nuproj_ files (or many other files, for that matter), this really isn't that helpful, and
2. Who'd think to add the NuProj project to a _*.nuproj_ anyway?
So I suppose this is of limited to no value. But it was quick and easy, so it's up to you. Maybe there's another way to surface this file. It would be nice not to have to manually hard-code the path to the NuProj local package directory since updating the package wouldn't fix it.
If we can assume or otherwise detect the solution package cache directory, we could use the MSBuild property function to recursively find the path. Potentially slow, though.
> Automatically set up NuProjPath

- docs/Authoring.md
Adding an example of the syntax to copy an entire file tree without
flattening
> Adding an example of the syntax to copy an entire file tree without flattening

- src/NuProj.Targets/NuProj.props
This change prevents the MSB4011 warning by checking if
`Microsoft.Common.props`  has already been imported.
Closes #295
> Prevent double import of Microsoft.Common.props
